version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Instalando dependencias..."
      - npm install
  build:
    commands:
      - echo "Compilando aplicaciones..."
      - |
        for app in admin client partner web; do
          cd apps/$app
          npm install
          npx vite build --base=/$app/
          cd ../..
        done
  post_build:
    commands:
      - echo "Sincronizando con S3 directamente..."
      - |
        for app in admin client partner web; do
          aws s3 sync apps/$app/dist s3://project-r-monorepos-bucket/$app --delete
        done

artifacts:
  files:
    - '**/*'
  base-directory: '.'