version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install
  build:
    commands:
      - echo "Iniciando build inteligente con Turbo..."
      # Compara el commit actual contra el anterior para filtrar
      - npx turbo build --filter=[HEAD^1] || npx turbo build
  post_build:
    commands:
      - |
        echo "Sincronizando con S3 según carpetas generadas..."
        for app in admin client partner web; do
          # Solo entra si la carpeta 'dist' existe (significa que esa app cambió)
          if [ -d "apps/$app/dist" ]; then
            echo "===> Actualizando S3 para: $app"
            aws s3 sync apps/$app/dist s3://project-r-monorepos-bucket/$app --delete
          fi
        done

artifacts:
  files: []