version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - npx turbo run build --filter=partner

artifacts:
  base-directory: 'apps/partner/dist'
  files:
    - '**/*'