version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - echo "Construyendo solo la app Admin..."
      - npx turbo run build --filter=admin

artifacts:
  base-directory: apps/admin/dist
  files:
    - '**/*'