version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install
  build:
    commands:
      - npx turbo run build --filter=commerce 

artifacts:
  base-directory: 'apps/commerce/out'
  files:
    - '**/*.html'
    - '**/*.js'
    - '**/*.css'
    - '**/*.json'
    - '**/*.svg'
    - '**/*.ico'
    - '**/*.png'
    - '**/*.jpg'
    - '_next/**/*'